CPPFLAGS = -Wall -g -std=c++17   # Opções do compilador: todos warnings e debug info

all: appgraph appdigraph appdfs appbfs appciclonaodirigido appciclodirigido apptopo

# classe Graph
appgraph = appgraph
appgraph_src = appgraph.cpp graph.cpp
appgraph_obj = $(appgraph_src:.cpp=.o)

# classe Digraph
appdgraph = appdigraph
appdgraph_src = appdigraph.cpp digraph.cpp graph.cpp
appdgraph_obj = $(appdgraph_src:.cpp=.o)

# DFS
appdfs = appdfs
appdfs_src = appdfs.cpp graph.cpp dfs.cpp
appdfs_obj = $(appdfs_src:.cpp=.o)

# BFS
appbfs = appbfs
appbfs_src = appbfs.cpp graph.cpp bfs.cpp
appbfs_obj = $(appbfs_src:.cpp=.o)

# Ciclos nao dirigidos
appciclonaodirigido = appciclonaodirigido
appciclonaodirigido_src = appciclonaodirigido.cpp ciclonaodirigido.cpp graph.cpp
appciclonaodirigido_obj = $(appciclonaodirigido_src:.cpp=.o)

# Ciclos dirigidos
appciclodirigido = appciclodirigido
appciclodirigido_src = appciclodirigido.cpp ciclodirigido.cpp digraph.cpp graph.cpp
appciclodirigido_obj = $(appciclodirigido_src:.cpp=.o)

# Ordem topologica
apptopo = apptopo
apptopo_src = apptopo.cpp ordtopologica.cpp digraph.cpp graph.cpp
apptopo_obj = $(apptopo_src:.cpp=.o)

$(appgraph): $(appgraph_obj)
	g++ $(CPPFLAGS) $(appgraph_obj) -o $@

$(appdgraph): $(appdgraph_obj)
	g++ $(CPPFLAGS) $(appdgraph_obj) -o $@

$(appdfs): $(appdfs_obj)
	g++ $(CPPFLAGS) $(appdfs_obj) -o $@

$(appbfs): $(appbfs_obj)
	g++ $(CPPFLAGS) $(appbfs_obj) -o $@

$(appciclonaodirigido): $(appciclonaodirigido_obj)
	g++ $(CPPFLAGS) $(appciclonaodirigido_obj) -o $@

$(appciclodirigido): $(appciclodirigido_obj)
	g++ $(CPPFLAGS) $(appciclodirigido_obj) -o $@

$(apptopo): $(apptopo_obj)
	g++ $(CPPFLAGS) $(apptopo_obj) -o $@

clean:
	-@ rm -f $(appgraph_obj) $(appgraph) $(appdgraph_obj) $(appdgraph) \
		   $(appdfs_obj) $(appdfs) \
			 $(appbfs_obj) $(appbfs) \
			 $(appciclonaodirigido_obj) $(appciclonaodirigido) \
			 $(appciclodirigido_obj) $(appciclodirigido) \
			 $(apptopo_obj) $(apptopo)


	   	
